### ISSUE TITLE
how to use procedural mysqli 

### ISSUE THREAD

**Issue by sevketk** [noahheck/E_mysqli#11]
can we use this utility , procedural mysqli ?

**Comment by noahheck** [comment]
@sevketk I don't think there's any reason you can't use this tool using procedural function calls. The `Emysqli` class extends the `mysqli` one, so anything you can do with the base one should work with this one.

There's a [page on the PHP manual](https://www.php.net/manual/en/mysqli.quickstart.dual-interface.php) that describes the dual interface available for the mysqli extension. In the third example (Bad coding style), they demonstrate how the two interfaces can be used at the same time. That's likely the approach you'd need to take when using E_mysqli procedurally.

I imagine the implementation would look something like this:

```php
<?php

require_once "path/to/vendor/autoload.php";

$mysqli = new EMysqli\EMysqli($dbHost, $dbUser, $dbPassword, $dbName);

$results = mysqli_query($mysqli, "SELECT name, email FROM users WHERE ...");
```
