### ISSUE TITLE
issue with bind_param function

### ISSUE THREAD

**Issue by Antjac** [noahheck/E_mysqli#2]
Hi, 

I've dectected an issue by using bind_param function. 
By exemple, after calling : bind_param(iis,$param1,$param2,$param3)

my variable $param1 is transformed into an array contening other parameters.

It is a problem if I want to reuser this parameter in another query...

**Comment by noahheck** [comment]
Haha, you're right! I initially wrote this for PHP 5.5 and wasn't able to implement that functionality correectly (look at the comment here: https://github.com/noahheck/E_mysqli/blob/master/E_mysqli.php#L81).

I can plan to put some additional work into this in a couple weeks.

**Comment by noahheck** [comment]
As I remembered, we're not able to access variable length argument lists by reference (a requirement of mysqli) without incidentally overwriting the first argument ($param1). We will be able to do this after the updates I mentioned in my last comment.

While I understand this isn't the ideal workflow, you should be able to properly generate the interpolated query string by binding the parameters one at a time:

```php
$stmt->bind_param("i", $param1);
$stmt->bind_param("i", $param2);
$stmt->bind_param("s", $param3);
```

This won't overwrite your input variable while allowing you to generate the query string.

**Comment by noahheck** [comment]
I have finally been able to get to updating this project as I intended. The requirements for the project have been significantly updated (php-5.0 -> php-5.6), but the functionality is much better now.

If you have other issues, make sure to let me know :)

Thanks again.
