### ISSUE TITLE
Best practice to insert multiple rows at once?

### ISSUE THREAD

**Issue by tobip** [noahheck/E_mysqli#9]
First of all thank you for this great library, it helps a lot in my workflow!

Now, I want to `INSERT` more than one row at the same time, using something like this:

    INSERT INTO table_name (ref_key, value) VALUES
        ROW(123, 'value_1'),
        ROW(123, 'value_2'),
        ROW(123, 'value_3');

In this case `ref_key` would always be the same, stored in the variable `$ref_key = 123`,   
and the value would be different for each row, stored in the array `$values = ['value_1', 'value_2', 'value_3']`.

Is it possible to build a mysql statement like this using E_mysqli?

**Comment by noahheck** [comment]
Thanks! I'm glad you find this package helpful.

One way I've approached this situation might be something like the following:

```php
<?php

// Establish your EMysqli connection here

$paramTypes = '';
$parameters = [];

$rows = [
    ['John', 'Doe', 'john@example.com'],
    ['Mary', 'Swanson', 'mary@example.com'],
];

$query = "INSERT INTO contacts (firstName, lastName, email) VALUES ";

foreach ($rows as $row) {
    $query .= ($paramTypes) ? ', ' : ''; // The first iteration through should not include the ,
    $query .= '(?,?,?)';
    $paramTypes .= 'sss';
    $parameters[] = $row[0];
    $parameters[] = $row[1];
    $parameters[] = $row[2];
}

// $query now looks like this: INSERT INTO contacts (firstName, lastName, email) VALUES (?,?,?), (?,?,?)
// $paramTypes now looks like this: ssssss
// $parameters now looks like this: ['John', 'Doe', 'john@example.com', 'Mary', 'Swanson', 'mary@example.com']

$stmt = $emysqli->prepare($query);

array_unshift($parameters, $paramTypes);// $parameters now looks like this: ['ssssss', 'John', 'Doe', 'john@example.com', 'Mary', 'Swanson', 'mary@example.com'] - Necessary for the call_user_func_array below

call_user_func_array([$stmt, 'bindParam'], $parameters); // Calls $stmt->bindParam with the arguments in $parameters

$stmt->execute();
```

Alternatively, as mentioned [here](https://github.com/noahheck/E_mysqli#further-enhancements), you could build the query and bind the arguments in separate steps if that helps clarify it for you:

```php
<?php

$rows = [...];

$query = "INSERT INTO contacts (firstName, lastName, email) VALUES " . implode(', ', array_fill(0, count($rows), '(?,?,?)'));
// $query now looks like this: INSERT INTO contacts (firstName, lastName, email) VALUES (?,?,?), (?,?,?)

$stmt = $emysqli->prepare($query);

foreach ($rows as $row) {
    $stmt->bindParam('s', $row[0]);
    $stmt->bindParam('s', $row[1]);
    $stmt->bindParam('s', $row[2]);
}

$stmt->execute();
```

The second option here certainly looks cleaner to me, but both methods should work well.

I hope this helps!

**Comment by tobip** [comment]
Thank you very much, this helps me understand it much better! :+1:
